teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 0
      y: 2
      z: 6
    scale_linear:
      x: 0.7
      y: 0.7
      z: 0.7
    scale_linear_turbo:
      x: 1.5
      y: 1.5
      z: 1.5
    axis_angular:
      yaw: 5
      pitch: 7
      roll: 3
    scale_angular:
      yaw: 0.4
      pitch: 0.4
      roll: 0.4

    enable_button: 8 # L2 shoulder button
    enable_turbo_button: 10 # L1 shoulder button
